#### New to Plotly?
Plotly's Python library is free and open source! [Get started](https://plot.ly/python/getting-started/) by downloading the client and [reading the primer](https://plot.ly/python/getting-started/).
<br>You can set up Plotly to work in [online](https://plot.ly/python/getting-started/#initialization-for-online-plotting) or [offline](https://plot.ly/python/getting-started/#initialization-for-offline-plotting) mode, or in [jupyter notebooks](https://plot.ly/python/getting-started/#start-plotting-online).
<br>We also have a quick-reference [cheatsheet](https://images.plot.ly/plotly-documentation/images/python_cheat_sheet.pdf) (new!) to help you get started!

### Imports
This tutorial imports [Numpy](http://www.numpy.org/).

In [66]:
import numpy as np
np.__version__

'1.11.2'

#### Linspace to Meshgrid

The `np.meshgrid()` function makes an N-D coordinate grid and often is used to pass `linspace` and `arange` arrays as their arguments.

In [93]:
nx, ny = (50, 50)

In [94]:
x = np.linspace(0, 10, nx)

In [95]:
y = np.linspace(0, 10, ny)

In [96]:
xv, yv = np.meshgrid(x, y)

In [100]:
zip?

In [99]:
zip(xv)

[(array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
           0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
           1.63265306,   1.83673469,   2.04081633,   2.24489796,
           2.44897959,   2.65306122,   2.85714286,   3.06122449,
           3.26530612,   3.46938776,   3.67346939,   3.87755102,
           4.08163265,   4.28571429,   4.48979592,   4.69387755,
           4.89795918,   5.10204082,   5.30612245,   5.51020408,
           5.71428571,   5.91836735,   6.12244898,   6.32653061,
           6.53061224,   6.73469388,   6.93877551,   7.14285714,
           7.34693878,   7.55102041,   7.75510204,   7.95918367,
           8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
           8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
           9.79591837,  10.        ]),),
 (array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
           0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
           1.63265306,   1.83673469,   2.04081633

In [50]:
yv

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [ 10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,
         10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,
         10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,
         10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,
         10.,  10.,  10.,  10.,  10.,  10.]])

In [64]:
x = np.arange(-5, 5, 0.2)
y = np.arange(-5, 5, 0.2)
xx, yy = meshgrid(x, y, sparse=True)
z = np.sin(xx**2 + yy**2) / (xx**2 + yy**2)

array([ -5.00000000e+00,  -4.80000000e+00,  -4.60000000e+00,
        -4.40000000e+00,  -4.20000000e+00,  -4.00000000e+00,
        -3.80000000e+00,  -3.60000000e+00,  -3.40000000e+00,
        -3.20000000e+00,  -3.00000000e+00,  -2.80000000e+00,
        -2.60000000e+00,  -2.40000000e+00,  -2.20000000e+00,
        -2.00000000e+00,  -1.80000000e+00,  -1.60000000e+00,
        -1.40000000e+00,  -1.20000000e+00,  -1.00000000e+00,
        -8.00000000e-01,  -6.00000000e-01,  -4.00000000e-01,
        -2.00000000e-01,   4.44089210e-15,   2.00000000e-01,
         4.00000000e-01,   6.00000000e-01,   8.00000000e-01,
         1.00000000e+00,   1.20000000e+00,   1.40000000e+00,
         1.60000000e+00,   1.80000000e+00,   2.00000000e+00,
         2.20000000e+00,   2.40000000e+00,   2.60000000e+00,
         2.80000000e+00,   3.00000000e+00,   3.20000000e+00,
         3.40000000e+00,   3.60000000e+00,   3.80000000e+00,
         4.00000000e+00,   4.20000000e+00,   4.40000000e+00,
         4.60000000e+00,

In [86]:
x = np.arange(-5, 5, 0.2)
y = np.arange(-5, 5, 0.2)
xx, yy = np.meshgrid(x, y, sparse=True)
z = np.sin(xx**2 + yy**2) / (xx**2 + yy**2)

In [89]:
z

array([[-0.0052475 , -0.01651205,  0.01779498, ...,  0.00831349,
         0.01779498, -0.01651205],
       [-0.01651205,  0.01875796,  0.00488659, ..., -0.02358335,
         0.00488659,  0.01875796],
       [ 0.01779498,  0.00488659, -0.02353064, ...,  0.00777974,
        -0.02353064,  0.00488659],
       ..., 
       [ 0.00831349, -0.02358335,  0.00777974, ...,  0.02201892,
         0.00777974, -0.02358335],
       [ 0.01779498,  0.00488659, -0.02353064, ...,  0.00777974,
        -0.02353064,  0.00488659],
       [-0.01651205,  0.01875796,  0.00488659, ..., -0.02358335,
         0.00488659,  0.01875796]])

In [84]:
z[50]

IndexError: index 50 is out of bounds for axis 0 with size 50

In [69]:
import plotly.plotly as py
import plotly.graph_objs as go

x = np.arange(-5, 5, 0.2)
y = np.arange(-5, 5, 0.2)
xx, yy = np.meshgrid(x, y, sparse=True)
z = np.sin(xx**2 + yy**2) / (xx**2 + yy**2)

trace1 = go.Scatter3d(
    x=x,
    y=y,
    z=z,
    mode='markers',
    marker=dict(
        size=12,
        line=dict(
            color='rgba(217, 217, 217, 0.14)'
        ),
        opacity=0.8
    )
)

data = [trace1]
py.iplot(data, filename='numpy-meshgrid')

In [28]:
x

array([ 1.08332498,  0.22608153,  1.32062933, -0.18202673, -1.0818413 ,
       -1.11236853,  1.11369313,  0.67503664,  1.06172221, -0.31817395,
        0.73879742,  0.08427009,  0.31514157,  1.66709778,  0.0694239 ,
       -1.02731556, -0.77784196,  1.0828742 ,  0.02165122, -0.59681603,
        0.04717574,  0.29282678, -0.63149735, -0.98494178, -0.0081165 ,
       -0.31204915,  0.44469292,  0.14010799,  2.20506715, -1.63238249,
       -0.69918531,  1.06331453, -1.49377491, -0.6100375 ,  1.41378329,
        0.23013305,  0.64411973, -0.53026635,  1.39629564,  0.94436488,
       -1.67162151, -1.03258469, -0.14903105, -0.80310982, -1.07309885,
       -0.05457387,  0.68525997, -0.52893523, -1.02516704, -1.85977421,
       -1.25396104, -0.35759884, -0.1463356 , -1.03720705,  0.66967381,
        1.028479  ,  0.91438228, -0.42848219, -0.59361578,  0.46961932,
       -0.61297718,  0.63967251,  0.29170979, -2.06279307,  2.11493098,
        0.73609285,  1.82445388,  1.59780915, -0.85333292, -0.34

#### Making a Plot

In [5]:
import plotly.plotly as py
import plotly.graph_objs as go

x = np.arange(0, 100)
y = np.arange(0, 100)

trace = go.Scatter(x=x, y=y, mode='markers')
py.iplot([trace], filename='numpy-arange')

In [6]:
from IPython.display import display, HTML

display(HTML('<link href="//fonts.googleapis.com/css?family=Open+Sans:600,400,300,200|Inconsolata|Ubuntu+Mono:400,700" rel="stylesheet" type="text/css" />'))
display(HTML('<link rel="stylesheet" type="text/css" href="http://help.plot.ly/documentation/all_static/css/ipython-notebook-custom.css">'))

! pip install git+https://github.com/plotly/publisher.git --upgrade
import publisher
publisher.publish(
    'Meshgrid.ipynb', 'numpy/meshgrid/', 'Meshgrid | plotly',
    'How to create a Meshgrid NumPy array.',
    title = 'Meshgrid | plotly',
    name = 'Meshgrid',
    has_thumbnail='true', thumbnail='thumbnail/numpy_array.jpg',
    language='numpy', page_type='example_index',
    display_as='numpy-array', order=4)

  Cloning https://github.com/plotly/publisher.git to /var/folders/tc/bs9g6vrd36q74m5t8h9cgphh0000gn/T/pip-RK_KOv-build
  Found existing installation: publisher 0.10
    Uninstalling publisher-0.10:
      Successfully uninstalled publisher-0.10
  Running setup.py install for publisher ... - \ done


/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/nbconvert.py:13: ShimWarning:

The `IPython.nbconvert` package has been deprecated. You should import from nbconvert instead.

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/publisher/publisher.py:53: UserWarning:

Did you "Save" this notebook before running this command? Remember to save, always save.

