#### New to Plotly?
Plotly's Python library is free and open source! [Get started](https://plot.ly/python/getting-started/) by downloading the client and [reading the primer](https://plot.ly/python/getting-started/).
<br>You can set up Plotly to work in [online](https://plot.ly/python/getting-started/#initialization-for-online-plotting) or [offline](https://plot.ly/python/getting-started/#initialization-for-offline-plotting) mode, or in [jupyter notebooks](https://plot.ly/python/getting-started/#start-plotting-online).
<br>We also have a quick-reference [cheatsheet](https://images.plot.ly/plotly-documentation/images/python_cheat_sheet.pdf) (new!) to help you get started!

### Imports
This tutorial imports [Numpy](http://www.numpy.org/).

In [1]:
import numpy as np
np.__version__

'1.11.2'

#### Basic Slicing and Indexing

`Indexing` a NumPy array is very similar to indexing a standard Python List. That is to say, most functionality of Python lists transfers over to NumPy arrays.

Single value indexing works the same way:

In [2]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17])
array[12]

12

A negative number as your index is interpreted as counting backwards from the end of the array:

In [3]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17])
array[-2]

16

Slicing also works the same way, similar to the principle behind how NumPy functions like `np.linspace()` construct an array based on `start`, `stop` and `step` parameters:

In [4]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17])
array[1:14:2]

array([ 1,  3,  5,  7,  9, 11, 13])

If an index of the form `x:` is used, all values past `x` will be returned:

In [5]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17])
array[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

And building on top of that, a `start` and `step` can be specified with `end` left blank:

In [6]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17])
array[5: :2]

array([ 5,  7,  9, 11, 13, 15, 17])

#### Integer Array Indexing
You can index an ND-array with a index of the form:

$$
\begin{align*}
[[r_1, ... , r_n], [c_1, ... , c_n]]
\end{align*}
$$

where $n$ can be any number. The values $r_1$ and $c_1$ respresent the row number and the column number to select from in order to pick a value to populate our new indexed array. For example, if $r_1$ is 1 and $c_1$ is 2, then we take the element in row 2 and column 3 of our original array and that will be our first value.

In [7]:
array = np.array([['a', 'b', 'c'],
                  ['d', 'e', 'f'],
                  ['g', 'h', 'i']])
array[[1],
      [2]]

array(['f'], 
      dtype='|S1')

We can use a larger $n$ to index a larger array:

In [8]:
array = np.array([['a', 'b', 'c'],
                  ['d', 'e', 'f'],
                  ['g', 'h', 'i']])
array[[0, 1, 0, 0, 2],
      [1, 1, 0, 2, 1]]

array(['b', 'e', 'a', 'c', 'h'], 
      dtype='|S1')

#### Boolean Indexing
Indexing can also function with a Boolean statement:

In [9]:
array = np.array([[0, 1, 2],
                  [3, 4, 5],
                  [6, 7, 8]])
array[array >= 4]

array([4, 5, 6, 7, 8])

In [1]:
from IPython.display import display, HTML

display(HTML('<link href="//fonts.googleapis.com/css?family=Open+Sans:600,400,300,200|Inconsolata|Ubuntu+Mono:400,700" rel="stylesheet" type="text/css" />'))
display(HTML('<link rel="stylesheet" type="text/css" href="http://help.plot.ly/documentation/all_static/css/ipython-notebook-custom.css">'))

! pip install git+https://github.com/plotly/publisher.git --upgrade
import publisher
publisher.publish(
    'Indexing.ipynb', 'numpy/indexing/', 'Indexing | plotly',
    'The basics of indexing NumPy arrays.',
    title = 'Numpy Indexing | plotly',
    name = 'Indexing',
    has_thumbnail='true', thumbnail='thumbnail/modify_the_array.jpg', 
    language='numpy', page_type='example_index', redirect_from='numpy/index/',
    display_as='modify-the-array', order=4)

  Cloning https://github.com/plotly/publisher.git to /private/var/folders/tc/bs9g6vrd36q74m5t8h9cgphh0000gn/T/pip-4lefyV-build
  Found existing installation: publisher 0.10
    Uninstalling publisher-0.10:
      Successfully uninstalled publisher-0.10
  Running setup.py install for publisher ... - done


/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/nbconvert.py:13: ShimWarning: The `IPython.nbconvert` package has been deprecated. You should import from nbconvert instead.
  "You should import from nbconvert instead.", ShimWarning)
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/publisher/publisher.py:53: UserWarning: Did you "Save" this notebook before running this command? Remember to save, always save.
  warnings.warn('Did you "Save" this notebook before running this command? '
